version: "3.8"

x-app: &base
  build:
    context: Docker Image
    dockerfile: Dockerfile
  restart: always
services:
  runnerone:
    <<: *base
    volumes:
      - ./data/runnerone/_work:/home/docker/actions-runner/_work:rw
    environment:
      - REPO=3A-s-Studio
      - REG_TOKEN=ABEEE3MIZMOU2AM6I4ISCMDJDREPM
      - NAME=RunnerOne
  # runnertwo:
  #   <<: *base
  #   environment:
  #     - REPO=3A-s-Studio
  #     - REG_TOKEN=ABEEE3O4KOPBUDJU24B4H5TJCOTVG
  #     - NAME=OrgRunnerTwo
  rpersonal:
    <<: *base
    environment:
      - REPO=triasbrata/WallpaperApp
      - REG_TOKEN=ABEEE3OCRCH322AMTLOGS6TJDREFO
      - NAME=RunnerTwo
